using System;

namespace Tiler.Model
{
    /// <summary>
    /// Immutable in-memory representation of a Heightmap Engine output file (.heightmap).
    ///
    /// This class is intentionally simple:
    /// - It stores only raw heights (0–255) and terrain layer classification bytes.
    /// - It performs ZERO normalization, smoothing, or procedural logic.
    /// - It exists to provide a clean, stable input contract for the Tiler stage.
    ///
    /// Coordinate conventions:
    /// - Cells are indexed using [x, y]
    /// - x increases to the right
    /// - y increases downward
    /// - (0,0) is the top-left cell
    ///
    /// The data is loaded from row-major byte streams in the file, but is exposed
    /// as [x,y] arrays for clarity.
    /// </summary>
    public sealed class HeightmapData
    {
        /// <summary>
        /// Width of the map in CELLS.
        /// </summary>
        public uint WidthInCells { get; }

        /// <summary>
        /// Height of the map in CELLS.
        /// </summary>
        public uint HeightInCells { get; }

        /// <summary>
        /// Deterministic seed generated by the Heightmap stage.
        ///
        /// The Tiler does not use this to generate anything.
        /// It is included for provenance, debugging, and future cross-stage verification.
        /// </summary>
        public ulong DeterministicSeed { get; }

        /// <summary>
        /// Cell heights, 0–255 inclusive, indexed as Heights[x, y].
        ///
        /// IMPORTANT:
        /// - These heights are already normalized and smoothed upstream.
        /// - The Tiler MUST NOT renormalize or resmooth them.
        /// </summary>
        public byte[,] Heights { get; }

        /// <summary>
        /// Terrain layer classification per cell, indexed as TerrainLayers[x, y].
        ///
        /// These values MUST be in the inclusive range [0..3] matching the TerrainLayer enum.
        /// They are authoritative classifications emitted by the Heightmap stage.
        /// </summary>
        public TerrainLayer[,] TerrainLayers { get; }

        /// <summary>
        /// Creates an immutable HeightmapData container.
        ///
        /// This constructor assumes inputs are already validated.
        /// Generally, you should obtain HeightmapData via HeightmapReader.Read(...).
        /// </summary>
        /// <param name="widthInCells">Map width in cells (must be > 0).</param>
        /// <param name="heightInCells">Map height in cells (must be > 0).</param>
        /// <param name="deterministicSeed">Deterministic seed copied from file.</param>
        /// <param name="heights">Cell heights array indexed as [x,y].</param>
        /// <param name="terrainLayers">Terrain layers array indexed as [x,y].</param>
        public HeightmapData(
            uint widthInCells,
            uint heightInCells,
            ulong deterministicSeed,
            byte[,] heights,
            TerrainLayer[,] terrainLayers)
        {
            WidthInCells = widthInCells;
            HeightInCells = heightInCells;
            DeterministicSeed = deterministicSeed;
            Heights = heights;
            TerrainLayers = terrainLayers;
        }
    }
}
