using MapGen.Application.WorldGeneration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;

namespace MapGen.Application;

/// <summary>
/// Composition root for the application layer. Registers Mediator and every
/// <c>IRequestHandler</c> in this assembly (ADR 0005). Hosts — the CLI and MapGen.Api
/// today, a worker host later — call this instead of constructing handlers by hand.
/// </summary>
public static class DependencyInjection
{
    public static IServiceCollection AddMapGenApplication(this IServiceCollection services)
    {
        // Mediator resolves every handler when the first request is sent, so this root has
        // to be self-sufficient: a host that only uses the tile commands (the CLI) must not
        // have to know about world-generation collaborators. Hosts that do care register
        // their own before or after this call and win — TryAdd defers to them.
        services.TryAddSingleton(TimeProvider.System);
        services.TryAddSingleton(new WorldGenerationOptions());
        services.TryAddSingleton<IGoldenJobSource, NoGoldenJobs>();
        services.TryAddSingleton<WorldJobRegistry>();

        // AddMediator is generated by Mediator.SourceGenerator; it discovers handlers
        // in this assembly and registers ISender/IMediator.
        services.AddMediator(options => options.ServiceLifetime = ServiceLifetime.Singleton);
        return services;
    }
}
