using Microsoft.Extensions.DependencyInjection;

namespace MapGen.Application;

/// <summary>
/// Composition root for the application layer. Registers Mediator and every
/// <c>IRequestHandler</c> in this assembly (ADR 0005). Hosts — the CLI today, the
/// worker host later — call this instead of constructing handlers by hand.
/// </summary>
public static class DependencyInjection
{
    public static IServiceCollection AddMapGenApplication(this IServiceCollection services)
    {
        // AddMediator is generated by Mediator.SourceGenerator; it discovers handlers
        // in this assembly and registers ISender/IMediator.
        services.AddMediator(options => options.ServiceLifetime = ServiceLifetime.Singleton);
        return services;
    }
}
